# Config file for BloodAST
# Advanced Server Tools provided by bCloud (http://blood-cloud.com)
# Messed up the config? Missing the comments? Get the original config.yml from GitHub!
# https://github.com/aerobless/BloodAST/blob/master/BloodAST/src/config.yml
# Feedback? Drop me an e-mail at "theo@w1nter.com".

#Chose which modules you want to have enabled
#----------------------
EnableStatisticsModule: true
EnableRewardModule: true
EnablePunishmentModule: true

#SQL Connection Information
#----------------------
#You need to have SQL configured for the statistics module and for making bans/warnings etc. visible on your website.
EnableSQL: true
Host: localhost
Port: 3306
Database: bloodAST
Username: yourDatabaseUser
Password: yourDatabaseUsersPassword

#GENERAL SETTINGS
#----------------------
#Set to false once your happy with your configuration and certain everything works. --> less messages in console
LogDebugMessagesToConsole: true
#Needs to be unique in a multi-server environment. E.g. bcloud_survival
ServerName: yourservername
#The URL of the bloodAST folder that you put on your webserver E.g. http://yourhost.com/bloodAST/
WebServerURL: http://yourhost.com/bloodAST
#OP's are allowed to use all commands even if they don't have the correct permission.
OPCanUseAllCommands: true

#STATISTICS SETTINGS
#----------------------
#How often do you want to update your statistics page in minutes. More often = more cpu usage & database storage required.
StatisticsUpdatePeriod: 4

#REWARD SETTINGS
#----------------------
#This text is displayed to the player when he has been online for the duration of the RewardPeriod.
RewardText: To thank you for playing on servername we sent you 50 dollars to spend in our ingame shop!
#How much ingame money do you want to give the player after each reward period?
RewardAmount: 50
#After how many minutes do you want to reward your players?
RewardGivePeriod: 29
#How often do we check if the reward-condition (^^) has been met?
RewardCheckPeriod: 4

#PUNISHMENT SETTINGS
#----------------------
