name: BloodAST
main: ch.theowinter.BloodAST.MainBloodAST
version: 1
depend: [iConomy]

commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
   warn:
      description: Warn players when they do something wrong.
      usage: /<command> [player] [warn text]